before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi

script: 
  - .travis/script.sh

# blocklist
branches:
  except:
  
# safelist
branches:
  only:
    - master
    - stable

matrix:
  include:
    - os: osx
      env: BUILD_TARGET=osx
      language: c

    - os: linux
      env: BUILD_TARGET=linux
      language: c

    - os: windows
      env: BUILD_TARGET=windows
      language: c

    - os: linux
      language: android
      env: BUILD_TARGET=android
      android:
        components:
          - android-26
          - build-tools-26.0.2
          - sys-img-arm64-android-26
          - sys-img-armeabi-v7a-android-26