# blocklist
branches:
  except:
  
# safelist
branches:
  only:
    - master
    - stable

matrix:
  include:
    - os: osx
      env: BUILD_TARGET=osx
      language: c
      script: cd unit_tests/gmake && make && make clean

    - os: linux
      env: BUILD_TARGET=linux
      language: c
      script: cd unit_tests/gmake && make && make clean

    - os: windows
      env: BUILD_TARGET=windows
      language: c
      before_install: choco install make
      script: cd unit_tests/gmake && make && make clean

    - os: linux
      language: android
      env: BUILD_TARGET=android
      script: cd unit_tests/gmake && make && make clean
      
      install:
        - yes | sdkmanager "ndk-bundle" &>/dev/null

        # Download emulator
        - yes | sdkmanager "platforms;android-19" &>/dev/null
        - yes | sdkmanager "system-images;android-19;default;armeabi-v7a" &>/dev/null

        # Setup emulator
        - echo "no" | avdmanager create avd -n test -k "system-images;android-19;default;armeabi-v7a" -c 200M -f &>/dev/null
        - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window & &>/dev/null
      
      before_script:
        - android-wait-for-emulator

        # Turn off animations
        - adb shell settings put global window_animation_scale 0 &
        - adb shell settings put global transition_animation_scale 0 &
        - adb shell settings put global animator_duration_scale 0 & 

        # Wake up
        - adb shell input keyevent 82 &

        - adb shell "ls /storage"
        - adb shell "ls /storage/self"
        - adb shell "ls /storage/primary"

      android:
        components:
          - android-26
          - build-tools-26.0.2
          - sys-img-arm64-android-26
          - sys-img-armeabi-v7a-android-26