language: c

before_install: if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi

script: cd unit_tests/gmake && make && make clean

# blocklist
branches:
  except:
  
# safelist
branches:
  only:
    - master
    - stable

matrix:
  include:
    - os: osx
    - os: linux
    - os: windows