name: Unit Tests CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move to unit tests folder
      run: cd unit_tests/gmake
    - name: Start unit tests
      run: make
